env_id: UTTTRLSim-v0
n_envs: 2
total_steps: 500
seed: 42

ppo_params:
  learning_rate: 0.0003
  batch_size: 128
  n_steps: 128
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  policy_kwargs:
    net_arch: [ 64, 64 ]

# ログとモデル保存の設定
tensorboard_log: logs/tb
model_path: models/policy.zip
log_interval: 1
